### ISSUE TITLE
[Feature request] - Unsubscribe/unregister for a course

### ISSUE THREAD

**Issue by Sarawilliams123** [MicrosoftDocs/community-content#133]
if someone registers for a course, but then it is no longer relevant to be able to unregister

**Comment by carlyrevier** [comment]
@Sarawilliams123 - I'm reviewing the issues you opened, but they appear to be for a different product, not for the community content contained within this repo. What product are you trying to file issues for?

**Comment by Sarawilliams123** [comment]
@carlyrevier its for the community training platform

https://learn.microsoft.com/en-us/azure/industry/training-services/microsoft-community-training/get-started/microsoft-community-training-overview

**Comment by carlyrevier** [comment]
@Sarawilliams123 - Thank you. Please leave feedback for this content using the "Feedback" control at the top of the page: 

![image](https://github.com/MicrosoftDocs/community-content/assets/23123030/ca3de298-b17e-4764-a90b-17c7140d1a42)

This will ensure that your feedback gets to the team who writes this documentation and owns the feature. The repo you've submitted these issues on is unrelated to the team that manages this content and feature. Thank you.
