### ISSUE TITLE
Customer feedback - Bearer token creation is outdated

### ISSUE THREAD

**Issue by KiriLucas** [MicrosoftDocs/community-content#184]
### Type of issue

Other (describe below)

### Feedback

It seems the provided documentation on how to create a Bearer token for API usage is outdated. It also lacks of some details, and a non experienced/non admin user may not be able to follow it. I was able to accomplish my goals because I've been using the CLI (and Azure's services) for a couple of years now, but I'm afraid it may be a blocker to some other users.

To prove it's outdated, the following command mentioned after logging in trough the CLI doesn't accept a `displayName` anymore as it used to: `az ad sp create-for-rbac -n "Azure_Service_Principal_Name"`, looking further showed that this command had a breaking change, but that's not mentioned in the doc.

Documentation mentioned: https://learn.microsoft.com/en-us/community/content/azure-rest-api-how-to-create-a-bearer-token#create-the-bearer-token

### Page URL

https://learn.microsoft.com/en-us/community/content/azure-rest-api-how-to-create-a-bearer-token

### Content source URL

https://github.com/MicrosoftDocs/community-content/blob/live/community-content/content/azure-rest-api-how-to-create-a-bearer-token.md

### Author

@gxgrammatikos

### Document Id

281cde5f-d3ef-932f-12f0-d01c721f8d01

**Comment by pdebruin** [comment]
Thanks for reporting the issue, @KiriLucas. 🙏 We are experimenting with this repository. Let's see how this goes. 

@gxgrammatikos, could you take a look at this?

**Comment by gxgrammatikos** [comment]
Thank you for reporting this @KiriLucas 🙏 . 
@pdebruin I have checked the CLI commands, and they need to update in the first step. I ran the rest of the commands, and they worked as expected. Please see the screenshot below: 

![image](https://github.com/user-attachments/assets/7aaf6301-c969-43b2-a289-6f09af312c39)

**Comment by KiriLucas** [comment]
That's awesome! Thank you guys!
