### ISSUE TITLE
Customer feedback - 

### ISSUE THREAD

**Issue by sheikjerbouti** [MicrosoftDocs/community-content#196]
### Type of issue

Fix or update for existing article

### Feedback

The kernel seems not "compilable" if you do not have the .config file. with the modules to configure/load 

cp Microsoft/config-wsl .config 

### Page URL

https://learn.microsoft.com/en-us/community/content/wsl-user-msft-kernel-v6

### Content source URL

https://github.com/MicrosoftDocs/community-content/blob/live/community-content/content/wsl-user-msft-kernel-v6.md

### Author

@NicoLiberato

### Document Id

928b1744-97a1-54be-d49d-59103599fcf3

**Comment by pdebruin** [comment]
Hi @NicoLiberato, thanks for reporting. Can you share at what point exactly you ran into an issue? And is your cp command a missing step that we should add where?

CC @gxgrammatikos

**Comment by gxgrammatikos** [comment]
@NicoLiberato  - Thanks for reporting. I have checked the article and spotted an issue with the command "cp arch/x86/boot/bzImage /mnt/c/" where it copies the bzimage file to the c: Is this what you have raised?
Apparently, it's a permissions issue as it is not allowed to copy from an external drive to C:, in your case, virtual storage.
I solved the issue by copying the file from "\\wsl$\Ubuntu\home\george\WSL2-Linux-Kernel\arch\x86\boot\bzImage" to C:. Other than that, I didn't experience any problem with the guide, so is this the issue you encountered? If so, I can update the article.

**Comment by NicoLiberato** [comment]
Hi @pdebruin \
it's happening when you pull/compile a "fresh" kernel  , in between point 4. and 5.

**Comment by pdebruin** [comment]
This doesn't happen in my environment: 
Win11 24H2 26100.2033
WSL 2.3.24.0
Ubuntu 24.04.1 LTS
Can you share details of your environment?

**Comment by NicoLiberato** [comment]
Yep:
WSL version: 2.3.24.0
Windows 11 Pro 23H2 22631.4317
Ubuntu 24.04.1 LTS

coming from a standard Ubuntu24.04 installation using WSL2
